version: "2"
linters:
  enable:
    - exhaustive
    - staticcheck
    - unused
    - gocritic
    - misspell
  disable:
    - errcheck
  exclusions:
    paths:
      - node_modules
formatters:
  enable:
    - gofmt
    - goimports
